name: flutter_series
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/images.jpeg
    - Assets/image/profile.jpeg
    - Assets/Data/info.json
  fonts:
    - family: Roboto
      fonts:
        - asset: Assets/Fonts/RobotoFont/Roboto-Black.ttf
        - asset: Assets/Fonts/RobotoFont/Roboto-BlackItalic.ttf
          style: italic
        - asset: Assets/Fonts/RobotoFont/Roboto-Bold.ttf
        - asset: Assets/Fonts/RobotoFont/Roboto-BoldItalic.ttf
          style: italic
        - asset: Assets/Fonts/RobotoFont/Roboto-Italic.ttf
          style: italic
        - asset: Assets/Fonts/RobotoFont/Roboto-Light.ttf
        - asset: Assets/Fonts/RobotoFont/Roboto-LightItalic.ttf
          style: italic
        - asset: Assets/Fonts/RobotoFont/Roboto-Medium.ttf
        - asset: Assets/Fonts/RobotoFont/Roboto-MediumItalic.ttf
          style: italic
        - asset: Assets/Fonts/RobotoFont/Roboto-Regular.ttf
        - asset: Assets/Fonts/RobotoFont/Roboto-Thin.ttf
        - asset: Assets/Fonts/RobotoFont/Roboto-ThinItalic.ttf
          style: italic